// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyYfo_49uPqNEIPBkDXB7qXcFWoGkbrNQ',
    appId: '1:113339482370:web:64c09f42853bdb555f821b',
    messagingSenderId: '113339482370',
    projectId: 'ecampus-e338f',
    authDomain: 'ecampus-e338f.firebaseapp.com',
    databaseURL: 'https://ecampus-e338f-default-rtdb.firebaseio.com',
    storageBucket: 'ecampus-e338f.firebasestorage.app',
    measurementId: 'G-ZMX5D4KJXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfWsfZd1UvQYkSYoY0eKZhwExQ4Es5AqM',
    appId: '1:113339482370:android:1f53c0d77bb7f6205f821b',
    messagingSenderId: '113339482370',
    projectId: 'ecampus-e338f',
    databaseURL: 'https://ecampus-e338f-default-rtdb.firebaseio.com',
    storageBucket: 'ecampus-e338f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDunI23zH-xVPMbr20UeQQDOMCzNEnFIiU',
    appId: '1:113339482370:ios:b456188abfaabb4e5f821b',
    messagingSenderId: '113339482370',
    projectId: 'ecampus-e338f',
    databaseURL: 'https://ecampus-e338f-default-rtdb.firebaseio.com',
    storageBucket: 'ecampus-e338f.firebasestorage.app',
    iosBundleId: 'com.example.campuspay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDunI23zH-xVPMbr20UeQQDOMCzNEnFIiU',
    appId: '1:113339482370:ios:b456188abfaabb4e5f821b',
    messagingSenderId: '113339482370',
    projectId: 'ecampus-e338f',
    databaseURL: 'https://ecampus-e338f-default-rtdb.firebaseio.com',
    storageBucket: 'ecampus-e338f.firebasestorage.app',
    iosBundleId: 'com.example.campuspay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyYfo_49uPqNEIPBkDXB7qXcFWoGkbrNQ',
    appId: '1:113339482370:web:64b3f974553364625f821b',
    messagingSenderId: '113339482370',
    projectId: 'ecampus-e338f',
    authDomain: 'ecampus-e338f.firebaseapp.com',
    databaseURL: 'https://ecampus-e338f-default-rtdb.firebaseio.com',
    storageBucket: 'ecampus-e338f.firebasestorage.app',
    measurementId: 'G-FPH2HFZ1N7',
  );
}
